### PR TITLE
Create an edit aligned text mode - visual editor - step 1

### PR DESCRIPTION
**Pull request by irina060981**
For the issue #39 - the first step

- created tokens editor
image

- created available actions : update a token word, merge with a left token, merge with a right token, split a token to two separate tokens
- created popup menu for these actions
image

- tokens in align editor are updated synchronously

Also some small fixes:
- fixed Reset All styles - https://github.com/alpheios-project/alignment-editor-new/issues/86#issuecomment-755309784
- fixed Download error message when textarea is empty - https://github.com/alpheios-project/alignment-editor-new/issues/86#issuecomment-757409465

### CODE REVIEW

**Comment by irina060981** [comment]
@balmas , this is the first step in tokens editor. The main aim of it is to check my vision of how it would look like and work.
That's why there are no comments and tests for now.

I would add them in the next PR.

**Comment by irina060981** [comment]
@balmas , Build is fixed - would be glad to your feedback :)

**Review by balmas — APPROVED** [review]
I like the way it looks. It's simple and easy to understand. I don't know how much of the underlying code you intend to be working at this point, so I didn't review it closely. I will add a few comments on the requirements:

1. as we discussed in the check-in, if it's not too much work, I would like to make the possibility to edit the text of a token a configurable option.  With the current UI design, this would mean restricting the edit to insertion of a space for the split token functionality.  

2. I am not sure of the best way to deal with the restriction on editing tokens which have already been aligned. This is something we will need to get user feedback on. But, going with the approach you have taken for now, I think we should visually identify those tokens that cannot be edited by not outlining them, and having a popup help which says that they need to be un-aligned before they can be edited.

3. For the token ids,I see that you have a `freeIdWord` getter on segment that isn't used yet.  I would like for us to be able to differentiate the ids of tokens which have been created or changed via the editor from tokens that were part of the original tokenization, and if possible, retain some sort of history. What do you think about the following approach:
 tokens which are merged get new Ids in the format <segment-id>-<original-token-id>-m-<increment>
 tokens which are split each get new ids in the format   <segment-id>-<original-token-id>-s-<increment>
 tokens which are edited each get new ids in the format   <segment-id>-<original-token-id>-e-<increment>

 tokens which are added at the beginning or end of a segment get ids in the format   <segment-id>-x-<increment>

so as an example, take the following segment of words "Bella per Emathios plus quam ciuilia" 

It has the following tokens (pseudo-code):

```
[ { text: 'Bella',
    id: '1-1',
    index: 0
  },
  { text: 'per',
     id '1-2',
    index: 1
  },
  { text: 'Emathios',
    id: '1-3',
    index: 2
  },
  { text: 'plus',
    id: '1-4',
    index: 3
  },
  { text: 'quam',
    id: '1-5',
    index: 4
  },
  { text: 'ciuilia',
    id: '1-6',
    index: 5
  }
]
```

Use merges 'plus' and 'quam', and we then have:


```
[ { text: 'Bella',
    id: '1-1',
    index: 0,
  },
  { text: 'per',
     id '1-2',
    index: 1,
  },
  { text: 'Emathios',
    id: '1-3',
    index: 2,
  },
  { text: 'plusquam',
    id: '1-4-m-1',
    index: 3,
  },
  { text: 'ciuilia',
    id: '1-6',
    index: 4,
  }
]
```

Use splits 'Emathios' after 'Em' and we then have:


```
[ { text: 'Bella',
    id: '1-1',
    index: 0
  },
  { text: 'per',
     id '1-2',
    index: 1
  },
  { text: 'Em',
    id: '1-3-s1',
    index: 2
  },
  { text: 'athios',
    id: '1-3-s2',
    index: 3
  },
  { text: 'plusquam',
    id: '1-4-m1',
    index: 4
  },
  { text: 'ciuilia',
    id: '1-6',
    index: 5
  }
]
```

User changes their mind and merges 'Em' and 'athios' back together, so we have:


```
[ { text: 'Bella',
    id: '1-1',
    index: 0
  },
  { text: 'per',
     id '1-2',
    index: 1
  },
  { text: 'Emathios',
    id: '1-3-s-1-m-1',
    index: 2,
  },
  { text: 'plusquam',
    id: '1-4-m-1',
    index: 3,
  },
  { text: 'ciuilia',
    id: '1-6',
    index: 4
  }
]
```

And so on. what do you think?

**Comment by irina060981** [comment]
@balmas - I moved discussion to the issue - and will merge these changes to the master branch .

**Pull request merged**
