### PR TITLE
Added information about version and build number

### PR DESCRIPTION
**Pull request by kirlat**
There seems to be no changes required to add the version information: the plugin to inject it is already in the `node-build` version used by the alignment editor. So I've just added assignments to demonstrate how it can be used; please consider it as an example.

This is in response to #88.

### CODE REVIEW

**Comment by balmas** [comment]
@kirlat so this is already there in the current alignment-editor build setup? And we would just also need to have a github-build.mjs script that outputs the buildName for the tagging workflow if and when we want to add that?

**Comment by kirlat** [comment]
> @kirlat so this is already there in the current alignment-editor build setup? And we would just also need to have a github-build.mjs script that outputs the buildName for the tagging workflow if and when we want to add that?

Yes, that's correct.

The plugin that injects the build info is already included into the version of the `node-build` that the alignment editor is using and it is active by default. I believe adding `github-build.mjs` would be all that is needed in order to support the tagging workflow.

**Comment by balmas** [comment]
> > @kirlat so this is already there in the current alignment-editor build setup? And we would just also need to have a github-build.mjs script that outputs the buildName for the tagging workflow if and when we want to add that?
> 
> Yes, that's correct.
> 
> The plugin that injects the build info is already included into the version of the `node-build` that the alignment editor is using and it is active by default. I believe adding `github-build.mjs` would be all that is needed in order to support the tagging workflow.

Great, thank you. @irina060981 I'll leave it to you to test and merge the PR.

**Comment by irina060981** [comment]
Thank you @kirlat and @balmas :)

**Pull request merged**
